name: mangadex
description: Wrapper for MangaDex API.
version: 0.0.1
homepage: https://github.com/TesteurManiak/flutter_manga_reader
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"

resolution: workspace

dependencies:
  clock:
  collection:
  freezed_annotation:
  intl:
  json_annotation:
  manga_reader_core:
    path: ../manga_reader_core
  path:

dev_dependencies:
  build_runner: ^2.7.1
  fd_lints: ^3.0.0
  freezed:
  json_serializable: ^6.11.2
